"""Initial Migration4

Revision ID: 3ff1cd6e8c91
Revises: 3a58d33a6c8c
Create Date: 2021-09-21 17:41:25.060989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ff1cd6e8c91'
down_revision = '3a58d33a6c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
