"""ionitial migration1

Revision ID: 467c0882e9d6
Revises: b278a65cc670
Create Date: 2021-09-19 12:29:28.516166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467c0882e9d6'
down_revision = 'b278a65cc670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
