"""Initial Migration4

Revision ID: 9f102cac13af
Revises: a511e5ed8edc
Create Date: 2021-09-20 18:46:47.964878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f102cac13af'
down_revision = 'a511e5ed8edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilepicpath', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilepicpath')
    # ### end Alembic commands ###
